sudo: required

services:
  - docker

before_install:
  - docker build -t sindhubasavanna/react-test -f ./client/Dockerfile.dev ./client
  # can build multiple things

script:
  - docker run sindhubasavanna/react-test npm test -- --coverage

after_success:
  - docker run -t sindhubasavanna/multi-client ./client
  - docker run -t sindhubasavanna/multi-nginx ./nginx
  - docker run -t sindhubasavanna/multi-server ./server
  - docker run -t sindhubasavanna/multi-worker ./worker
#Login to the docker CLI
#Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin

  - docker push sindhubasavanna/multi-client
  - docker push sindhubasavanna/multi-nginx
  - docker push sindhubasavanna/multi-server
  - docker push sindhubasavanna/multi-worker